<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<!-- 1. 目标框架：Windows专属 .NET10，支持WinForms/隐藏控制台 -->
		<TargetFramework>net10.0-windows</TargetFramework>

		<!-- 2. 开启可空类型检查，编译时校验null空值，减少空引用报错 -->
		<Nullable>enable</Nullable>

		<!-- 3. 隐式全局using，无需每个cs文件手动写using System;等基础命名空间 -->
		<ImplicitUsings>enable</ImplicitUsings>

		<UseWPF>true</UseWPF>
		<!-- 4. 输出类型：Windows窗体程序，运行不会弹出黑色cmd控制台窗口 -->
		<OutputType>WinExe</OutputType>

		<!-- 5. 启用Windows窗体依赖，配合WinExe实现隐藏控制台；必须搭配 -windows 框架 -->
		<UseWindowsForms>true</UseWindowsForms>

		<!-- 6. 指定exe程序文件图标，使用项目内Image文件夹下的app.ico -->
		<ApplicationIcon>Image\\app.ico</ApplicationIcon>
	</PropertyGroup>


	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.7" />
	</ItemGroup>


	<ItemGroup>
		<Page Include="App.xaml" />
	</ItemGroup>

	<!-- 配置ico文件自动复制到发布输出目录 -->

	<ItemGroup>
		<ProjectReference Include="..\SLD.Net10.Common\SLD.Net10.Common.csproj" />
		<ProjectReference Include="..\SLD.Net10.Communication\ConnectionMqtt\ConnectionMqtt.csproj" />
		<ProjectReference Include="..\SLD.Net10.Communication\ConnectModbusRtuWithTcp\ConnectionModbusRtuWithTcp.csproj" />
		<ProjectReference Include="..\SLD.Net10.Extension\SLD.Net10.Extension.csproj" />
		<ProjectReference Include="..\SLD.Net10.Model\SLD.Net10.Model.csproj" />
		<ProjectReference Include="..\SLD.Net10.Service\SLD.Net10.Service.csproj" />
	</ItemGroup>

	<!-- 确保 Image 目录下的图标文件复制到输出目录，供运行时托盘图标使用 -->
	<ItemGroup>
		<Content Include="Image\**" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
	</ItemGroup>

</Project>
